### ISSUE TITLE
[4.26][latest Marketplace version as of this issue][win64] Crash on launch

### ISSUE THREAD

**Issue by simonSlamka** [BrUnOXaVIeRLeiTE/SCUE4-Plugin#3]
Hey,

Having this plugin enabled causes an immediate crash when launching a packaged game (haven't tested standalone or PIE). Not even logs get created, so there's no simple way to find the issue. I am using 4.26 from the Epic launcher and the latest marketplace version of the plugin. I didn't change any settings, and I **have not** switched my gameinstance to the secure one.

Any ideas?

Thanks

**Comment by xcibe95x** [comment]
Same issue on 4.27.2, i have been building on this plugin just to discover it won't work in packaged builds, any solutions?

**Comment by simonSlamka** [comment]
> Same issue on 4.27.2, i have been building on this plugin just to discover it won't work in packaged builds, any solutions?

I moved on since and implemented my own solution.

Try attaching a debugger to the process and capture the crash. The callstack could provide some hints.

**Comment by BrUnOXaVIeRLeiTE** [comment]
I will investigating this weekend.
Usually the problem is wrong marketplace paths.

**Comment by BrUnOXaVIeRLeiTE** [comment]
By the way, I do not push patches to Unreal 4.26 anymore. Old engine which I don't work with anymore.

**Comment by simonSlamka** [comment]
> I will investigating this weekend. Usually the problem is wrong marketplace paths.

I checked the paths and also tried recompiling the plugin in my local project dir, but it didn't solve the issue,

**Comment by simonSlamka** [comment]
> By the way, I do not push patches to Unreal 4.26 anymore. Old engine which I don't work with anymore.

Fair point. Unfortunately, the project I'm working on is already in a state from which it cannot be ported to UE5 (hell, not even to UE4.27) without losing a bunch of functionality (which could be reimplemented, but that would take ages).

**Comment by BrUnOXaVIeRLeiTE** [comment]
You can uninstall the markeplace plugin and replace it with the plugin from GitHub.
You only need a small C++ knowledge to edit the source and edit engine version from the .uplugin file.

When you package, make sure that the additional SCUE4 folder and binaries have been copied to the packaged directory.
If they are not, you must copy them to the path that the output package was created.
This is why the plugin will force a shutdown, binaries are missing.

**Comment by simonSlamka** [comment]
> You can uninstall the markeplace plugin and replace it with the plugin from GitHub. You only need a small C++ knowledge to edit the source and edit engine version from the .uplugin file.
> 
> When you package, make sure that the additional SCUE4 folder and binaries have been copied to the packaged directory. If they are not, you must copy them to the path that the output package was created. This is why the plugin will force a shutdown, binaries are missing.

Thanks, but I no longer need it. @xcibe95x might, though.
Since this issue seems to have been resolved, I'm gonna close it. Thanks for making this plugin, @BrUnOXaVIeRLeiTE!
